services:
    db:
      image: postgres:16
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=reflection_user
        - POSTGRES_PASSWORD=reflection_user_2026
        - POSTGRES_DB=reflection_db
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    api:
      build: .
      ports:
        - 8000:8000
      depends_on:
        - db
      environment:
        - DATABASE_URL=postgresql://reflection_user:reflection_user_2026@db:5432/reflection_db
        - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    
    frontend:
      build: ./frontend
      ports:
        - 3000:3000
      depends_on:
        - api
      environment:
        - NEXT_PUBLIC_USER_ID=b2769e58-414b-4d6e-b7b2-643db1616bda
      

volumes:
  pgdata: