"""add message_context table

Revision ID: 005621077ea7
Revises: 5a268af96366
Create Date: 2026-04-02 20:56:33.741031

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "005621077ea7"
down_revision: Union[str, Sequence[str], None] = "5a268af96366"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_context",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("context_type", sa.String(length=30), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "context_type IN ('reflection')",
            name="ck__message_context__context_type",
        ),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id", "context_type", "context_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_context")
    # ### end Alembic commands ###
