"""add project model

Revision ID: 19a64c0ef4a2
Revises: 1ca3b586c00f
Create Date: 2026-05-06 16:19:17.238014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a64c0ef4a2'
down_revision: Union[str, Sequence[str], None] = '1ca3b586c00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_file',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'file_id')
    )
    op.create_table('project_system_prompt',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('system_prompt_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_prompt_id'], ['system_prompt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'system_prompt_id')
    )
    op.add_column('file', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'file', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('session', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'session', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('system_prompt', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'system_prompt', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_prompt', type_='foreignkey')
    op.drop_column('system_prompt', 'project_id')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'project_id')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'project_id')
    op.drop_table('project_system_prompt')
    op.drop_table('project_file')
    op.drop_table('project')
    # ### end Alembic commands ###
