"""add_type_to_system_prompt

Revision ID: 2fcb3f4848e4
Revises: 19a64c0ef4a2
Create Date: 2026-05-14 12:44:24.893121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fcb3f4848e4"
down_revision: Union[str, Sequence[str], None] = "19a64c0ef4a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_prompt",
        sa.Column(
            "type", sa.String(length=30), server_default="default", nullable=False
        ),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck__system_prompt__type",
        "system_prompt",
        "type IN ('default', 'periodic_weekly', 'periodic_monthly')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck__system_prompt__type", "system_prompt", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_prompt", "type")
    # ### end Alembic commands ###
