"""add prompt_id to session

Revision ID: 394ac9232ec6
Revises: 6691d809d1b9
Create Date: 2026-05-28 11:28:27.909928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394ac9232ec6'
down_revision: Union[str, Sequence[str], None] = '6691d809d1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('prompt_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk__session__prompt_id__system_prompt', 'session', 'system_prompt', ['prompt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk__session__prompt_id__system_prompt', 'session', type_='foreignkey')
    op.drop_column('session', 'prompt_id')
    # ### end Alembic commands ###
