"""add system_prompt table

Revision ID: 5a268af96366
Revises: 2beef748793d
Create Date: 2026-04-01 17:12:11.366388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a268af96366"
down_revision: Union[str, Sequence[str], None] = "2beef748793d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_prompt",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq__system_prompt__user_id_name"),
    )
    op.create_index(
        "uq__system_prompt__name__builtin",
        "system_prompt",
        ["name"],
        unique=True,
        postgresql_where=sa.text("user_id IS NULL"),
    )

    op.execute("""
        CREATE TRIGGER set_updated_at_system_prompt
        BEFORE UPDATE ON system_prompt
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq__system_prompt__name__builtin",
        table_name="system_prompt",
        postgresql_where=sa.text("user_id IS NULL"),
    )
    op.drop_table("system_prompt")
    op.execute("DROP TRIGGER IF EXISTS set_updated_at_system_prompt ON system_prompt")
    # ### end Alembic commands ###
