"""add_model_to_message_table

Revision ID: b352868f7f15
Revises: 394ac9232ec6
Create Date: 2026-06-19 11:41:32.033798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b352868f7f15"
down_revision: Union[str, Sequence[str], None] = "394ac9232ec6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("model", sa.String(50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "model")
    # ### end Alembic commands ###
